all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become_pass: "{{ sudo_password }}"
    
  groups:
    web_servers:
      hosts:
        akiba_server_prod:
          ansible_host: "{{ terraform_output_server_ip }}"
          server_env: production
    
    dev_servers:
      hosts:
        akiba_server_dev:
          ansible_host: localhost
          server_env: development
          ansible_connection: local
web_servers:
  vars:
    app_env: production
    deployment_user: appuser
    mongodb_root_user: "{{ mongodb_user | default('root') }}"
    mongodb_password: "{{ mongodb_password }}"
    mongo_db_name: "{{ mongo_db_name | default('akiba') }}"
    server_port: "{{ server_port | default(3000) }}"
    node_env: production
