[bastion]
bastion-host ansible_host=3.84.131.80 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/id_rsa

[app]
app-vm ansible_host=10.0.1.101

[app:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no -J ubuntu@3.84.131.80'
ansible_become=yes
ansible_python_interpreter=/usr/bin/python3
